#!/bin/bash
set -euo pipefail

BS_PATH=/usr/local/bootstrap

source "$BS_PATH/.env"
source "$BS_PATH/utilities/lg.sh"

if [ -z "${DEBUG:-}" ]; then
  exec 3>&1 &>/dev/null
else
  exec 3>&1
fi

explain() {
  cat <<EOT >&3
Uknown argument > Available options:
-x) Execute all scripts
-0) Execute 0-configure-self
-1) Execute 1-create-user
-2) Execute 2-install-packages
-3) Execute 3-user-shell
-4) Execute 4-docker-project
-5) Execute 5-dns-records
-6) Execute 6-cronjobs
EOT
}

while getopts ":x0123456" opt; do
  case $opt in
  \?)
    explain
    ;;
  x)
    lg '### BEGINNING BOOTSTRAP ###'
    find "$BS_PATH/scripts" -type f | while read script; do
      bash $script
    done
    lg '### BOOTSTRAP COMPLETED ###'
    ;;
  *)
    find "$BS_PATH/scripts" -type f -name "$opt-*" | while read script; do
      bash $script
    done
    ;;
  esac
done
