version: "3"
services:
  reverse-proxy:
    image: traefik:v2.0
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - volumes/reverse-proxy/traefik.yaml:/etc/traefik/traefik.yaml
      - volumes/reverse-proxy/acme.json:/acme.json
    environment:
      - DO_AUTH_TOKEN_FILE=/run/secrets/traefik_do-auth-token
