#!/bin/bash
set -euo pipefail
{
home_directory=
GITHUB_AUTH_TOKEN=

echo ">> Apt update"
for i in update {,dist-}upgrade auto{remove,clean}; do
  apt-get $i -y  &> /dev/null;
done

echo ">> Update bootstrap"
git -C "${home_directory}/bootstrap" pull -q

echo ">> Update non-apt apps"
{
git -C "${home_directory}/.fzf" pull -q
"${home_directory}/.fzf/install"

docker-compose -f "${home_directory}/docker/docker-compose.yml" down

curl -fsSL "https://github.com/docker/compose/releases/download/$(curl -fsSL https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
} &> /dev/null

echo ">> Create docker backup file"
tar -cpzf /tmp/docker.tar.gz -C "${home_directory}" docker

echo ">> Clear existing backup file from repo"
RELEASE_ID=$(curl -fsSL -H "Authorization: token ${GITHUB_AUTH_TOKEN}" https://api.github.com/repos/rabidpug/artifacts/releases/latest | jq .id)

ASSETS=($(curl -fsSL -H "Authorization: token ${GITHUB_AUTH_TOKEN}" "https://api.github.com/repos/rabidpug/artifacts/releases/${RELEASE_ID}/assets" | jq -c '.[] | . '))

for asset in $ASSETS; do 
  id=$(echo $asset | jq -r .id)
  curl -fsSL -X DELETE -H "Authorization: token ${GITHUB_AUTH_TOKEN}" "https://api.github.com/repos/rabidpug/artifacts/releases/assets/${id}";
done

echo ">> Upload new backup file to repo"
curl -fsSL -H "Authorization: token ${GITHUB_AUTH_TOKEN}" -H "Content-Type: application/octet-stream" --data-binary @/tmp/docker.tar.gz "https://uploads.github.com/repos/rabidpug/artifacts/releases/${RELEASE_ID}/assets?name=docker.tar.gz" > /dev/null

echo ">> Remove local backup file"
rm -f /tmp/docker.tar.gz

echo ">> Docker pull"
docker-compose -f "${home_directory}/docker/docker-compose.yml" pull > /dev/null

echo ">> Spin up docker"
docker-compose -f "${home_directory}/docker/docker-compose.yml" up -d &> /dev/null
} &> /var/log/update_backup.log