version: "3"
services:
  traefik:
    image: traefik:v2.0
    networks:
      - web
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/traefik/config:/etc/traefik
      - ./services/traefik/data/letsencrypt:/letsencrypt
    env_file: .env
  gitlab:
    image: gitlab/gitlab-ce
    networks:
      - web
      - internal
    restart: always
    hostname: jcuneo.com
    volumes:
      - ./services/gitlab/config:/etc/gitlab
      - ./services/gitlab/log:/var/log/gitlab
      - ./services/gitlab/data:/var/opt/gitlab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`jcuneo.com`,`www.jcuneo.com`)"
      - "traefik.http.routers.gitlab.entrypoints=webSecure"
      - "traefik.http.routers.gitlab.tls.certResolver=master"
  gitlab-runner-1:
    image: gitlab/gitlab-runner
    networks:
      - internal
    volumes:
      - ./volumes/repo/runner-1:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
  gitlab-runner-2:
    image: gitlab/gitlab-runner
    networks:
      - internal
    volumes:
      - ./volumes/repo/runner-2:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      
      
networks:
  web:
    external: true
  internal:
    internal: true
