providers:
  docker:
    network: web
api:
certificatesResolvers:
  master:
    acme:
      email: m@jcuneo.com
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: digitalocean
        delayBeforeCheck: 60
entryPoints:
  web:
    address: :80
  webSecure:
    address: :443
