providers:
  docker:
    network: web
api:
certificatesResolvers:
  master:
    acme:
      email: m@jcuneo.com
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: digitalocean
        delayBeforeCheck: 60
entryPoints:
  web:
    address: :80
  webSecure:
    address: :443
http:
  middlewares:
    secure-redirect:
      redirect-scheme:
        scheme: https
    admin:
      basicauth:
        users: admin:password
  routers:
    secure-redirect:
      rule: hostregexp(`{host:.+}`)
      entrypoints: web
      middlewares: secure-redirect
    traefik:
      rule: Host(`router.jcuneo.com`)
      service: api@internal
      middlewares: admin
      entrypoints: webSecure
      tls:
        certResolver: master
