http:
  middlewares:
    insecure-redirect:
      redirectScheme:
        scheme: https
    auth:
      basicAuth:
        usersFile: /etc/traefik/users.pw
  routers:
    insecure-redirect:
      rule: hostregexp(`{any:.+}`)
      entrypoints: web
      service: insecure-redirect
      middlewares:
        - insecure-redirect
    traefik:
      rule: Host(`router.jcuneo.com`)
      entrypoints: webSecure
      service: api@internal
      middlewares:
        - auth
      tls:
        certResolver: master
  services:
    insecure-redirect:
      loadBalancer:
        servers:
          - url: ""