providers:
  docker:
    network: web
    exposedByDefault: false
  file:
    filename: /etc/traefik/provider.yml
api:
  dashboard: true
certificatesResolvers:
  master:
    acme:
      email: m@jcuneo.com
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: digitalocean
        delayBeforeCheck: 60
entryPoints:
  web:
    address: ":80"
  webSecure:
    address: ":443"
  sshGitlab:
    address: ":23"
