#!/bin/bash
set -euo pipefail

BS_PATH=/usr/local/bootstrap

source "$BS_PATH/.env"
source "$BS_PATH/utilities/lg.sh"

lg '## BEGINNING CONFIGURING SELF ##'

lg 'Configure log'
touch /var/log/bs.log
cat <<EOT >>/etc/logrotate.d/bs
/var/log/bs.log {
daily
copytruncate
missingok
dateext
rotate 7
compress
}

EOT

lg 'Making script executable and adding to PATH'
chmod +x "$BS_PATH/bootstrap"
ln -sf "$BS_PATH/bootstrap" /usr/local/bin

lg '## CONFIGURING SELF COMPLETED COMPLETED ##'
