#!/bin/bash
set -euo pipefail

BS_PATH=/usr/local/bootstrap

source "$BS_PATH/.env"
source "$BS_PATH/utilities/lg.sh"

lg '## BEGINNING USER SHELL ##'
if [ -z "${USERNAME:-}" ]; then
  lg 'Skipping configuring user shell - No user'
else
  home_directory="$(eval echo ~$USERNAME)"

  lg 'Changing user shell to zsh'
  usermod -s "$(command -v zsh)" "$USERNAME"

  lg "Make sure user owns home dir"
  chown --recursive "$USERNAME:$USERNAME" "$home_directory"

  lg 'sourcing /etc/profile in .zshrc'
  su "$USERNAME" -c "echo 'source /etc/profile' >> $home_directory/.zshrc"

  lg 'Configuring git identity'
  su "$USERNAME" -c "git config --global user.email $GIT_EMAIL"
  su "$USERNAME" -c "git config --global user.name $GIT_NAME"

  lg 'Installing FZF'
  su "$USERNAME" -c "git clone -q https://github.com/junegunn/fzf.git $home_directory/.fzf && $home_directory/.fzf/install --all"

  lg 'Installing Antigen'
  su "$USERNAME" -c "git clone -q https://github.com/zsh-users/antigen.git $home_directory/antigen"

  find "$BS_PATH/dotfiles" -type f | while read dotfile; do
    lg "Adding/updating $(basename $dotfile) to .zshrc"
    ln -sf "$dotfile" "$home_directory"
    src="source \$HOME/$(basename $dotfile)"
    if ! grep -q "$src" "$home_directory/.zshrc"; then
      echo "$src" >>"$home_directory/.zshrc"
    fi
  done
fi

lg '## USER SHELL COMPLETED ##'
