#!/bin/bash
set -euo pipefail

BS_PATH=/usr/local/bootstrap

source "$BS_PATH/.env"
source "$BS_PATH/utilities/lg.sh"

lg '## BEGINNING DOCKER PROJECT ##'
if grep -Eq '/(lxc|docker|kubepods)/[[:xdigit:]]{64}' /proc/1/cgroup; then
  lg 'Skipping docker project setup - Code server'
elif [ -z "${USERNAME:-}" ]; then
  lg 'Skipping docker project setup - No user'
elif [ -z "${GITHUB_AUTH_TOKEN:-}" ]; then
  lg 'Skipping docker project setup - No auth token'
else
  home_directory="$(eval echo ~$USERNAME)"
  services_directory="$home_directory/docker/services"
  lg 'Getting asset release id'
  release_id=$(curl -fsSL -H "Authorization: token $GITHUB_AUTH_TOKEN" https://api.github.com/repos/rabidpug/artifacts/releases/latest | jq -r .id)

  lg 'Getting asset IDs'
  mapfile -t assets < <(curl -fsSL -H "Authorization: token $GITHUB_AUTH_TOKEN" "https://api.github.com/repos/rabidpug/artifacts/releases/$release_id/assets" | jq -c '.[] | {name: .name, id: .id, label: .label}')
mkdir -p "$services_directory"

  lg 'Creating docker Web network'
  docker network create web
    for asset in "${assets[@]}"; do
    id=$(echo "$asset" | jq -r .id)
    service=$(echo "$asset" | jq -r .label)
      lg "Downloading and extracting $service Docker assets"
      curl -fsSL -H "Authorization: token $GITHUB_AUTH_TOKEN" -H "Accept: application/octet-stream" "https://api.github.com/repos/rabidpug/artifacts/releases/assets/$id" | tar --same-owner -xzp -C "$services_directory"
      lg "Spinning up $service"
      docker-compose -f "$services_directory/$service/docker-compose.yml" up -d
  done

fi

lg '## DOCKER PROJECT COMPLETED ##'
