#!/bin/bash
set -euo pipefail

BS_PATH=/usr/local/bootstrap

source "$BS_PATH/.env"
source "$BS_PATH/utilities/lg.sh"

lg '## BEGINNING CRONJOBS ##'

find "$BS_PATH/cron/" -mindepth 1 -type d | while read folder; do
  interval=$(basename "$folder")
  find "$folder" -type f | while read job; do
    lg "Create symlink for $(basename $job) in cron.$interval"
    chmod +x "$job"
    ln -sf "$job" "/etc/cron.$interval"
  done
done
if grep -Eq '/(lxc|docker|kubepods)/[[:xdigit:]]{64}' /proc/1/cgroup; then
  lg 'Code server - leaving cronjobs at 6am'
else
  lg 'Setting cronjobs to run at 4am'
  sed -i 's/ 6\t/ 4\t/g' /etc/crontab
fi
lg '## CRONJOBS COMPLETED ##'
