#!/bin/bash
set -euo pipefail

BS_PATH=/usr/local/bootstrap

source "$BS_PATH/.env"
source "$BS_PATH/utilities/lg.sh"

lg '## BEGINNING CRONJOBS ##'

find "$BS_PATH/cron/" -mindepth 1 -type d | while read folder; do
  interval=$(basename "$folder")
  find "$folder" -type f | while read job; do
    lg "Create symlink for $(basename $job) in cron.$interval"
    chmod +x "$job"
    ln -sf "$job" "/etc/cron.$interval"
  done
done

lg '## CRONJOBS COMPLETED ##'
