#!/bin/bash
set -euo pipefail
{
  BS_PATH=/usr/local/bootstrap

  source "$BS_PATH/.env"
  source "$BS_PATH/utilities/lg.sh"

  if [ -z "${DEBUG:-}" ]; then
    exec 3>&1 &>/dev/null
  else
    exec 3>&1
  fi

  lg '## BEGINNING PACKAGES UPDATE ##'
  lg 'Apt update'
  export DEBIAN_FRONTEND=noninteractive
  for i in update {,dist-}upgrade auto{remove,clean}; do
    apt -y $i
  done

  if [ -z "$USERNAME" ]; then
    lg 'Skipping - no username provided'
  else
    home_directory="$(eval echo ~$USERNAME)"
    lg 'Update non-apt apps'
    git -C "$home_directory/.fzf" pull -q
    "$home_directory/.fzf/install" --all

    curl -fsSL "https://github.com/docker/compose/releases/download/$(curl -fsSL https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose

    if [ -d "$home_directory/docker/services" ]; then
      services_path="$home_directory/docker/services"
      find "$services_path" -mindepth 1 -maxdepth 1 -type d | while read folder; do
        service=$(basename "$folder")
        if [ -f "$services_path/$service/.directives" ]; then
          source "$services_path/$service/.directives"
        fi

        proceed=1
        down=0
        build=0
        case "1" in
        "${IDLE:-}")
          lg "$service is idle"
          proceed=0
          ;;
        "${DOWN:-}")
          lg "$service will come down during backup"
          down=1
          ;;
        "${BUILD:-}")
          lg "$service needs to be built"
          build=1
          ;;
        esac
        if [ "$proceed" = "1" ]; then
          if [ "$build" = "1" ]; then
            lg "build $service"
            docker-compose -f "$services_path/$service/docker-compose.yml" build
          fi
          lg "pull $service"
          docker-compose -f "$services_path/$service/docker-compose.yml" pull
          if [ "$down" = "0" ]; then
            lg "update $service"
            docker-compose -f "$services_path/$service/docker-compose.yml" up -d
          fi
        fi
        unset IDLE
        unset DOWN
        unset BUILD
      done
    else
      lg 'Skipping docker project update - No docker folder'
    fi
  fi

  lg '## PACKAGES UPDATE COMPLETED ##'

} &>>/var/log/bs.log
