#!/bin/bash
set -euo pipefail
{
  BS_PATH=/usr/local/bootstrap

  source "$BS_PATH/.env"
  source "$BS_PATH/utilities/lg.sh"

  if [ -z "${DEBUG:-}" ]; then
    exec 3>&1 &>/dev/null
  else
    exec 3>&1
  fi

  lg '## BEGINNING PACKAGES UPDATE ##'
  lg 'Apt update'
  export DEBIAN_FRONTEND=noninteractive
  for i in update {,dist-}upgrade auto{remove,clean}; do
    apt -y $i
  done

  if [ -z "$USERNAME" ]; then
    lg 'Skipping - no username provided'
  else
    home_directory="$(eval echo ~$USERNAME)"
    lg 'Update non-apt apps'
    git -C "$home_directory/.fzf" pull -q
    "$home_directory/.fzf/install" --all

    curl -fsSL "https://github.com/docker/compose/releases/download/$(curl -fsSL https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose

    if [ -d "$home_directory/docker" ]; then
      lg 'Docker build'
      docker-compose -f "$home_directory/docker/docker-compose.yml" build
      lg 'Docker pull'
      docker-compose -f "$home_directory/docker/docker-compose.yml" pull
    else
      lg 'Skipping docker project update - No docker folder'
    fi
  fi

  lg '## PACKAGES UPDATE COMPLETED ##'

} &>>/var/log/bs.log
